name: auto-assign-self-and-label
# action test
run-name: assign ${{ github.actor }} and add labels
on:
  pull_request:
    types:
      [opened, edited]
jobs:
  assign-self:
    runs-on: ubuntu-latest
    steps:
    - name: Assign self to the pull request
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}

  add-labels:
    name: Label the PR based on the label of the jira ticket.
    runs-on: ubuntu-latest
    outputs:
      ticket_no: ${{ steps.ticket_no.outputs.ticket_no }}
    steps:
      - name: Get Ticket Number
        id: ticket_no
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          TICKET_NO=$(echo "$TITLE" | grep -o '\[.*\]' | sed 's/\[\(.*\)\]/\1/')
          echo "ticket_no=$TICKET_NO" >> $GITHUB_OUTPUT
      
      - name: get ticket label
        run: echo "todo - get label from jira ticket ${{ steps.ticket_no.outputs.ticket_no }}"

      - name: add labels
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            const labelsToAdd = ["teamA"];
            const payload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labelsToAdd
            };
            await github.issues.addLabels(payload);