name: auto-assign-self-and-label
# action test
run-name: assign ${{ github.actor }} and add labels
on:
  pull_request:
    types:
      - opened
jobs:
  assign-self:
    runs-on: ubuntu-latest
    steps:
    - name: show pull_request
      run: echo "github.actor = ${{ github.actor}}, github.event.pull_request.user.login = ${{github.event.pull_request.user.login}}"