name: auto-assign-self-and-label
# action test
run-name: assign ${{ github.actor }} and add labels
on:
  pull_request:
    types:
      - opened
jobs:
  assign-self:
    runs-on: ubuntu-latest
    steps:
    - name: Assign self to the pull request
      run: |
        TOKEN=$GITHUB_TOKEN
        PR_NO=${{ github.event.pull_request.number }}
        USER=${{ github.actor }}
        
        curl -X POST \
        -H "Authorization: token $TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues/$PR_NO/assignees \
        -d '{"assignees":["'$USER'"]}'